# Generated by Django 5.0.2 on 2024-03-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionFinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
