# Generated by Django 5.0.2 on 2024-03-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionFinal', '0004_alter_apunte_materia_alter_libreria_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['nombre_empresa'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellido'], 'verbose_name': 'Empleado/a', 'verbose_name_plural': 'Empleados/as'},
        ),
    ]
