# Generated by Django 5.0.2 on 2024-03-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionFinal', '0005_alter_cliente_options_alter_contacto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libreria',
            options={'ordering': ['nombre_producto']},
        ),
    ]
