# Generated by Django 5.0.2 on 2024-03-29 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionFinal', '0007_alter_empleado_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinta',
            name='sublimacion',
        ),
    ]
