# Generated by Django 5.0.2 on 2024-03-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionFinal', '0008_remove_tinta_sublimacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papel',
            old_name='nombre_producto',
            new_name='marca',
        ),
    ]
