# Generated by Django 5.0.2 on 2024-03-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionFinal', '0009_rename_nombre_producto_papel_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinta',
            old_name='nombre_producto',
            new_name='marca',
        ),
    ]
